@hostname = https://localhost:7002

### 1. API ĐĂNG NHẬP ĐỂ LẤY TOKEN
POST {{hostname}}/api/auth/login
Content-Type: application/json

{
  "username": "aduanhduy",
  "password": "aduanhduydeptrai09"
}


### 2. TEST GỌI VÀO TRANG CREATE (NHỚ PHẢI CÓ 3 DẤU THĂNG PHÍA TRÊN)
GET {{hostname}}/Monan/Create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkdWFuaGR1eSIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTc4MDMzNTM2OSwiZXhwIjoxNzgwMzQ5NzY5LCJpYXQiOjE3ODAzMzUzNjksImlzcyI6IldlZGRpbmdIb3VzZVNlcnZlciIsImF1ZCI6IldlZGRpbmdIb3VzZUNsaWVudCJ9.gSMGpkjFR4WWkpgCl_6h_7XKO3u3hnP1jRlm5Acd0SU